### ISSUE TITLE
Proposal: Nerf pp if a large amount of players has the same play with mods

### ISSUE THREAD

**Issue by ShinyNinetalesTM** [ppy/osu-performance#29]
Explanation: we all know what maps are called "pp maps", and how overweighted are them. My proposal is the following: if the map has more than 50% of the player with the current mods FC, nerf the pp exponentially.
This means for example, if there are 1000 players that has HDHR a "X" beatmap, which 40%~50% or more of them are FC, pp should be nerfed in a short percentage. This could be also applied for SS in particular, nerfing even more the pp (in the same case if SS's were more than 50% of the plays in the map with the current mods)

Maybe I could explain it more detailed but in short words this is my proposal. I know it's easier to say it than doing it, but I guess it's actually the best way to balance the overweighted beatmaps.

**Comment by Tom94** [comment]
One core value of the current pp system is for each score to be rated _fully independently_ from the scores of other players. This has multiple reasons. To name a few:
- It prevents maps from being over or underrated exclusively due to popularity.
- Players' pp does not constantly change without them doing anything.
- It makes the technical realization of pp significantly simpler. A system where scores are rated in a mutually dependent manner requires constant reprocessing of all available data, which unfortunately is infeasible with the large number of scores osu! currently has.

Unfortunately I am not willing to compromise on these reasons with pp. If a more directly competetive system were to be implemented I would like to see it as a separate system which fully embraces the concept (perhaps similar to an ELO rating).

**Comment by Francesco149** [comment]
yeeah the map popularity thing was already attempted with ppv1 back in the day and it was pretty broken
