### ISSUE TITLE
OD/AR inaccuracies in beatmap difficulty attributes table

### ISSUE THREAD

**Issue by Rickput** [ppy/osu-performance#4]
After messing around some, I noticed that, with DT specifically, the table is not giving what should be the correct values for OD and AR.

http://puu.sh/os5ex/b5097957f2.png

This table is saying OD 8.5 +DT is OD 10.11, and AR 9.3 (labeled as 9.31?) is AR 10.54.

Using http://w.ppy.sh/8/88/ODTable.png for OD and https://i.ppy.sh/de463a31f71b68ea457cec732efad1e2e21513c7/687474703a2f2f772e7070792e73682f362f36382f41525461626c652e706e67 for AR as references, the DT OD for 8.5 should be 10.0833 (19ms) and the DT AR for 9.3 should be 10.5333 (370ms)

For the AR, this inaccuracy starts at the nomod value (9.31), which would be 10.54 with DT, as stated in the table.

For OD, the 8.5 is accurate for nomod but 10.11 is not accurate for DT.

Is this an error or is there a hidden explanation for this?

**Comment by Tom94** [comment]
Hi, thanks for the notice! I looked a bit into this and it turns out there are 2 things at work.

1. The millisecond timings from AR and OD are internally rounded to integers (it's the most granular timing the bass audio library gives us), and the AR and OD values stored in the DB relate exactly to these rounded milliseconds. This means, that AR and OD essentially always snap to some value that yields exact millisecond timings.

In the case of your particular map AR9.3 exactly maps to 555ms, so why is there a discrepancy? The answer is, that due to floating point inaccuracies AR9.3 actually maps to 554.999971389771ms, which gets rounded down to 554ms. Yup, whenever you play AR9.3 you actually play the equivalent of AR9.306666... . Entries in the DB are rounded to 2 decimal places, yielding AR9.31. I think that last rounding step is stupid, and thus I removed it just now.

2. The OD calculations of the pp client did not have the -0.5 modification built-in (which is related to bass and integer rounding again). I added the -0.5 modification to the display in song select a few months back, but totally forgot to adjust difficulty calculations to also take it into account. I also just fixed that.

That should fix your concerns. :)

**Comment by Rickput** [comment]
Alright, thanks for looking into it. Just to be clear, did these inaccuracies cause pp ratings for DT scores to be ever so slightly off? And if so, will we be seeing some minor changes to some DT score ratings?

**Comment by Tom94** [comment]
Yes, and yes.

**Comment by Rickput** [comment]
Thanks again. Looking forward to seeing that diff calc going open-source.
