### ISSUE TITLE
Decide on Doxygen comment format standard

### ISSUE THREAD

**Issue by Weikardzaena** [ppy/osu-performance#5]
If we're not going to be using Doxygen or other form of automatic documentation, then feel free to just close this.

Coming from a corporate setting I've always been told that comprehensively documenting your code is not an optional thing.  Doxygen makes it really easy to just whip up a PDF of all the methods and classes so people can reference stuff quickly, but if we start doing it we should stick to one comment standard.

Personally I don't really have a preference to which style is used ([some examples from the Doxygen manual](https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html)), but the easiest one IMO is the `///` block because Visual studio automagically fills in the necessary stuff when you type the `///`.  Thoughts?

**Comment by xxbidiao** [comment]
I personally guess that since this is not released either as a standalone or an API (Or to say, this is more of a project for review rather than a project for development), the development team haven't come to a point to comment this thoroughly.

Things like it from processor.cpp L252
`	std::string query = StrFormat(
		"SELECT `osu_beatmaps`.`beatmap_id`,`countNormal`,`mods`,`attrib_id`,`value`,`approved`,`score_version` "
		"FROM `osu_beatmaps` "
		"JOIN `osu_beatmap_difficulty_attribs` ON `osu_beatmaps`.`beatmap_id` = `osu_beatmap_difficulty_attribs`.`beatmap_id` "
		"WHERE `osu_beatmap_difficulty_attribs`.`mode`={0} AND `approved` >= 1",
		_gamemode);`
Clearly shows that there are other projects that this one strongly depends on. I wonder when will these projects be available (It seems that there is another repo supposed to host them).

**Comment by Tom94** [comment]
Due to the small scope of this project there are no official plans to provide documentation. The code should be very much self-explanatory, but of course we're happy to accept pull requests providing docs.
