### ISSUE TITLE
Acc rebalance for speed pp

### ISSUE THREAD

**Issue by MBmasher** [ppy/osu-performance#73]
(In collaboration with Dumii and VINXIS)

Acc scaling for speed pp right now is pretty terrible - it's linear. Also, the effect OD has on the scaling is pretty low. Things like this is what cause people to gain pp from doubletap plays on streamy EZDT maps (and this will soon be further amplified when Xexxar's speed buff goes through).

This is what me, Dumii and VINXIS has come up with. We have changed the old linear curve to a sigmoid curve. This means that everything under a certain acc threshold gets nerfed pretty harshly, while anything above gets a very slight buff. OD also has a large effect. If the OD is lower, that acc threshold becomes higher, and thus low acc plays are nerfed more. [Link to calculator in Desmos](https://www.desmos.com/calculator/v09xnfvwtf)

Here are examples of people's profiles with this change:

[Gayzmcgee - most of his plays get a slight buff as none of them are really low acc enough to get nerfed.](https://cdn.discordapp.com/attachments/292162221511802880/525983810576187392/unknown.png)
[exc - the maps in his top that get nerfed are EZHDDT plays which range from 80-90 acc.](https://cdn.discordapp.com/attachments/292162221511802880/525984111123496970/unknown.png)
[404 AimNotFound - The selected play in the screenshot is an EZDT play on a speed map with 87% acc.](https://cdn.discordapp.com/attachments/292162221511802880/525985489736433674/unknown.png)

Would be cool to hear some thoughts from the general community before we push this change further. Thank you for reading!

**Comment by MBmasher** [comment]
values have been changed to this: [desmos link](https://www.desmos.com/calculator/zufvyz2o7j)

**Comment by VINXIS** [comment]
We have tested values and have came up with this:

```cs
// Scale the speed value with accuracy. Harsher dropoff for lower acc.
            speedValue *= (
                1.0f / (
                    1 + Math.Pow(
                        Math.E, 
                        -20f * (accuracy + Math.Pow(Attributes.OverallDifficulty, 2.0f) / 2310.0f - 0.8733f
                    )))) / 1.89f + Math.Pow(Attributes.OverallDifficulty, 2.0f) / 5000.0f + 0.49f;```


this should replace

```cs
// Scale the speed value with accuracy _slightly_
            speedValue *= 0.5f + accuracy / 2.0f;
            // It is important to also consider accuracy difficulty when doing that
            speedValue *= 0.98f + Math.Pow(Attributes.OverallDifficulty, 2) / 2500;```

in the OsuPerformanceCalculator.cs file

**Comment by VINXIS** [comment]
sdhkgjfwersjkfewl forgot to post the test results https://puu.sh/ClLkJ/9e852000d8.txt

**Comment by diamondburned** [comment]
This is pretty harsh, can we maybe tone it down to `o=1.52` and `s=-7.3`?

**Comment by VINXIS** [comment]
Can I know why it's too harsh? This is based on accounting for the new speed and angle changes which ultimately change what is considered in the first place as a jump and a stream. As the new changes give much more weighting to streams and speed in speed.cs, accuracy is much more dependent on the property which is why we considered to change it to Show that

**Comment by MBmasher** [comment]
yeah... that was the point of this...

**Comment by diamondburned** [comment]
That's why I'm trying to suggest changes here?

**Comment by VINXIS** [comment]
The reason it's so harsh is because due to the angles + speed PR, the speed's definition has changed into a property which is HIGHLY dependent on accuracy, unlike aim. When you see a speed play on a map with low accuracy, people would consider that Performance nowhere near as impressive as the Performance of a speed play on a map with high accuracy. This is different with aim maps because accuracy in general is not as important in the Performance of a play heavily based on aim.

This is why low accuracy on speed maps should have much lower pp as a result. Other maps are not nearly as affected due to the fact that they are much more based on aim. I can give you comparison values if you'd really like. Here are values of plays before and after the acc nerf (with all other changes such as HD, FL, angles, speed, e.t.c implemented): https://docs.google.com/spreadsheets/d/1SqR1KODW39M1tVmGYS16JismDoc1M2jmNAwWfjgmh_w/edit#gid=0

**Comment by VINXIS** [comment]
Furthermore, you can check the scores on xexxar-all as it has this acc change implemented currently. Things don't look that bad to me.

**Comment by VINXIS** [comment]
A also added OD as that's also related

**Comment by visualer** [comment]
I don't get it. Does this affect only the "stream" part or the speed value of the whole map?

**Comment by VINXIS** [comment]
both as the speed property itself is changing its definition to become more inline to faster higher bpm streams instead with the angles + speed change

**Comment by visualer** [comment]
so assume that if there is a 6000 combo map and someone gets 99% from it, the 1% acc drop happening on a 300 bpm stream which most of its SR comes from and he doubletaps on. Will this refactor nerf the play to hell or just ignore it for its 99% acc?

**Comment by VINXIS** [comment]
No unless it was less than OD 4.3. Though I don't think anything could nerf that with any method as of right now since PP doesn't work that way :/

**Comment by visualer** [comment]
ok I got it. Many thanks for explanation :)
